const myVar = "a constant"

try {
    out.print("Attempting to do something which causes error")
    myVar = "new value"
    out.print(myVar)
} catch e {
    out.print("Gracefully handled an error:", e)
}

out.print("and that's how we handle errors, gracefully")
